In [1]:
import dask.array as da 
import numpy as np

In [4]:
arr = np.array([13], dtype=np.uint8)
arr

array([13], dtype=uint8)

In [5]:
np.invert(arr)

array([242], dtype=uint8)

In [7]:
np.binary_repr(13, width=8)

'00001101'

In [8]:
np.binary_repr(242)

'11110010'

In [10]:
darr = da.from_array(arr, chunks=1)

In [11]:
darr

dask.array<array, shape=(1,), dtype=uint8, chunksize=(1,)>

In [12]:
arr2 = np.array([13, 242], dtype=np.uint8)
arr2

array([ 13, 242], dtype=uint8)

In [13]:
np.invert(arr2)

array([242,  13], dtype=uint8)

In [18]:
da.bitwise_and(darr, darr).compute()

array([13], dtype=uint8)

In [19]:
arr

array([13], dtype=uint8)